"""Where reviews live: <root>/.code-review/reviews/<kind>-<id>-<YYYYMMDD>[-N]/

The reviews root is always the same; every review gets its own sub-folder. If the folder name
already exists a numeric suffix (-2, -3, ...) is appended so repeated reviews of the same code
never overwrite each other. mkdir is atomic, so concurrent runs cannot collide."""
import datetime
import os

from .errors import ReviewError
from .util import read_json, write_json, write_text


def reviews_root(repo_root, out_dir):
    if out_dir:
        return os.path.normpath(os.path.abspath(out_dir))
    return os.path.normpath(os.path.join(repo_root or os.getcwd(), ".code-review", "reviews"))


def ensure_root(root):
    os.makedirs(root, exist_ok=True)
    gi = os.path.join(root, ".gitignore")
    if not os.path.exists(gi):
        write_text(gi, "# generated by code-review; reviews are local artifacts\n*\n")


def alloc_dir(root, source_id, today=None):
    ensure_root(root)
    stamp = (today or datetime.date.today()).strftime("%Y%m%d")
    base = "%s-%s" % (source_id, stamp)
    for n in range(1, 1000):
        name = base if n == 1 else "%s-%d" % (base, n)
        path = os.path.join(root, name)
        try:
            os.mkdir(path)
            return path
        except FileExistsError:
            continue
    raise ReviewError("DIR_EXHAUSTED", "too many reviews named %s" % base)


def state_path(run_dir):
    return os.path.join(run_dir, "state.json")


def load_state(run_dir):
    p = state_path(run_dir)
    if not os.path.isfile(p):
        raise ReviewError("NOT_A_RUN", "not a review folder (state.json missing): %s" % run_dir)
    return read_json(p)


def save_state(run_dir, state):
    write_json(state_path(run_dir), state)


def same_diff_reviews(root, run_dir, diff_sha):
    """Other reviews of byte-identical diffs: [{name, verdict, fingerprint}] sorted by name."""
    out = []
    if not os.path.isdir(root):
        return out
    me = os.path.basename(run_dir)
    for name in sorted(os.listdir(root)):
        p = os.path.join(root, name, "report.json")
        if name == me or not os.path.isfile(p):
            continue
        try:
            r = read_json(p)
        except ValueError:
            continue
        if r.get("source", {}).get("diff_sha256") == diff_sha:
            out.append({"name": name, "verdict": r.get("verdict"), "fingerprint": r.get("fingerprint")})
    return out
